
server:
    port: 8186

spring:
    application:
        name: ZCY-SERVER
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/zcy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

        initialization-mode: always

        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        druid:
            web-stat-filter:
                enabled: true
                url-pattern: "/*"
                exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

        stat-view-servlet:
                url-pattern: "/druid/*"
                #  禁用HTML页面上的“Reset All”功能
                reset-enable: false
                allow: 127.0.0.1,*
                login-username: admin
                login-password: 123456
    jpa:
        # 在 SrpingBoot 2.0 版本中，Hibernate 创建数据表的时候，默认的数据库存储引擎选择的是 MyISAM
        #（之前好像是 InnoDB，这点比较诡异）。这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的。
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        # spring.jpa.show-sql=true 配置在日志中打印出执行的 SQL 语句信息。
        show-sql: true
        # 配置指明在程序启动的时候要删除并且创建实体类对应的表。
        # create 这个参数很危险，因为他会把对应的表删除掉然后重建。所以千万不要在生成环境中使用。只有在测试环境中，一开始初始化数据库结构的时候才能使用一次。
        # ddl-auto:create----每次运行该程序，没有表格会新建表格，表内有数据会清空
        # ddl-auto:create-drop----每次程序结束的时候会清空表
        # ddl-auto:update----每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新(推荐)
        # ddl-auto:validate----运行程序会校验数据与数据库的字段类型是否相同，不同会报错
        hibernate:
            ddl-auto: validate


    mvc:
        view:
            prefix: /
            suffix: /

    http:
        encoding:
            force: true
            charset: utf-8
            enabled: true

---
spring:
    redis:  ###### redis 配置
        host: 127.0.0.1  # ip地址
        port: 6379  # 端口号
        password: # 无密码不填
        timeout: 30000s   # 连接超时时间 （默认1天）
        lettuce:
            pool: # lettuce 连接池
                max-active: 8 # 连接池最大连接数 默认 8（-1 ：表示没有限制）
                max-wait: 60000ms # 连接池最大阻塞等待时间 默认-1ms （-1 :表示没有限制） 这里设置1分钟
                max-idle: 8 # 最大空闲连接  默认 8
                min-idle: 0 # 最小空闲连接  默认 0

---
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: test
        password: test2020
        virtual-host: /

---
logging:
    level:
        com.ascendant: debug
eureka:
    instance:
        hostname: localhost
#        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

spring:
    security:
        user:
            name: admin
            password: admin

# 授权访问
feign:
    httpclient:
        enabled: true
