
server:
    port: 8550

spring:
    application:
        name: CALCULATE-SERVER

---
logging:
    level:
        com.ascendant: debug

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

# 授权访问
feign:
    httpclient:
        enabled: true


#暴露全部的监控信息
management:
    endpoints:
        web:
            exposure:
                include: '*'
